### ISSUE TITLE
Confusing `touch` and `enableDragHandle` props

### ISSUE THREAD

**Issue by ArtemSerga** [react-component/m-drawer#7]
1. To enable swipe action - I should set both `touch={true} enableDragHandle={true}`. Why?
1. But swipe back - doesn't work. BUG?
1. If I set `touch={false} enableDragHandle={true}` - swipe action doesn't work.
1. I completely misunderstand what is the `touch` prop purpose.

**Comment by warmhug** [comment]
There is no problem, the `touch` prop is only for more granular control. Such as mobile phone support touch events, but you can still disable the touch function.

**Comment by ArtemSerga** [comment]
Is there a way to swipe back opened drawer?

**Comment by warmhug** [comment]
Sorry for not yet.

**Comment by ArtemSerga** [comment]
@warmhug thanks for quick response!
I close this issue and create new feauture request https://github.com/react-component/drawer/issues/8
