### ISSUE TITLE
Needs to drag twice to open the drawer when used with fastclick

### ISSUE THREAD

**Issue by jddxf** [react-component/m-drawer#9]
Steps to reproduce:

1. Set `enableDragHandle` to true.
2. Open the drawer and click the overlay to close it.
3. Now it needs two drags to open the drawer.

The reason is that when used with fastclick the `onTouchEnd` handler didn't get executed, leaving `this.notTouch` remaining `true`.Thus a first drag trying to open the drawer wouldn't work as `touchIdentifier` is set to `null`.
https://github.com/react-component/drawer/blob/b9c133893baf8ddb4a3f50a8444cd64cf21474a4/src/Drawer.jsx#L384-L391
https://github.com/react-component/drawer/blob/b9c133893baf8ddb4a3f50a8444cd64cf21474a4/src/Drawer.jsx#L148-L149
https://github.com/react-component/drawer/blob/b9c133893baf8ddb4a3f50a8444cd64cf21474a4/src/Drawer.jsx#L118-L123

Possible solutions:

- Allow to add `needsclick` class to the overlay node.
- Maybe we don't need to attach touch handlers when the drawer is open since we don't support swipe back.
- Maybe use `this.props.open` instead of `this.notTouch` to determine a valid touch.

**Comment by eternalsky** [comment]
@benjycui @afc163 @warmhug
